apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service-deployment
  labels:
    app: accounts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
      - name: accounts-service
        image: avinashghodke/accounts-service:v1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
