services:
  accounts:
    image: "avinashghodke/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - infinity
networks:
  infinity:
    driver: "bridge"